### ISSUE TITLE
git clone command to build

### ISSUE THREAD

**Issue by MariaChakchurina** [Loki-Astari/ThorsSerializer#27]
`> git clone git@github.com:Loki-Astari/ThorsSerializer.git`
There must be a mistake, correct command is  
`> git clone https://github.com/Loki-Astari/ThorsSerializer.git`

**Comment by Loki-Astari** [comment]
No. The correct command is:
> git clone git@github.com:Loki-Astari/ThorsSerializer.git

The https version is using password authentication (which is very insecure).
The git@ version is using your ssh key that you registered with github (much better security).

All the setup scripts assume you have an ssh key registered with github (otherwise you need to authenticate manually multiple times) as it downloads all the sub projects.

See: https://help.github.com/articles/generating-an-ssh-key/
